//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;
using System.Collections;

namespace AssemblyCSharp
{
	public class Interactable : GameObject
	{

		public float objTimeScale = 1f; //default speed of all objects
		private float slowTime = 0.2f; //multiplier to add the slow effect of yellow souls

		public Vector3 objMovementVector; //movement vector for the levitation effect of blue souls

		public bool alwaysIndestructible; //for objects that are always indestructible or annihilator
		public bool alwaysAnnihilator;

		public bool isIndestructible; //tell if the object is indestructible/annihilator
		public bool isAnnihilator;

		public Interactable objectHit; //stores the colliding object

		public Interactable ()
		{
			Debug.Log ("Object is being created");
		}

		//slows down objects upon use of yellow souls
		void reduceObjTimeScale () 
		{
			if (this.objTimeScale == 1f) {
				this.objTimeScale *= slowTime;
			}
		}
		//restores normal movement speed to objects
		void restoreObjTimeScale () {
			if (this.objTimeScale == 0.2f) {
				this.objTimeScale /= slowTime;
			}
		}

		//toggles indestructible quality
		void toggleIndestructible ()
		{
			if (!this.alwaysIndestructible) {
				this.isIndestructible = ~this.isIndestructible;
			}
		}

		//toggles annihilator quality
		void toggleAnnihilator () 
		{
			if (!this.alwaysAnnihilator)
			this.isAnnihilator = ~this.isAnnihilator;
		}

		void OnCollisionEnter (Collision col) {
			objectHit = col.gameObject;
		}

		void annihilateNextTarget () {
			if (objectHit.isIndestructible == false) {
				//Animation.Play();
				Destroy(objectHit);
				if (!this.alwaysAnnihilator){
					this.isAnnihilator = false;
				}
			} 
		}
	}
}

